/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lftechnology.bijaydemo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the THAdmin service. Represents a row in the &quot;BJ_THAdmin&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lftechnology.bijaydemo.model.impl.THAdminModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lftechnology.bijaydemo.model.impl.THAdminImpl}.
 * </p>
 *
 * @author bijay
 * @see THAdmin
 * @see com.lftechnology.bijaydemo.model.impl.THAdminImpl
 * @see com.lftechnology.bijaydemo.model.impl.THAdminModelImpl
 * @generated
 */
public interface THAdminModel extends BaseModel<THAdmin> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t h admin model instance should use the {@link THAdmin} interface instead.
	 */

	/**
	 * Returns the primary key of this t h admin.
	 *
	 * @return the primary key of this t h admin
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t h admin.
	 *
	 * @param primaryKey the primary key of this t h admin
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this t h admin.
	 *
	 * @return the ID of this t h admin
	 */
	public long getId();

	/**
	 * Sets the ID of this t h admin.
	 *
	 * @param id the ID of this t h admin
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this t h admin.
	 *
	 * @return the company ID of this t h admin
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this t h admin.
	 *
	 * @param companyId the company ID of this t h admin
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this t h admin.
	 *
	 * @return the name of this t h admin
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this t h admin.
	 *
	 * @param name the name of this t h admin
	 */
	public void setName(String name);

	/**
	 * Returns the password of this t h admin.
	 *
	 * @return the password of this t h admin
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this t h admin.
	 *
	 * @param password the password of this t h admin
	 */
	public void setPassword(String password);

	/**
	 * Returns the group ID of this t h admin.
	 *
	 * @return the group ID of this t h admin
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this t h admin.
	 *
	 * @param groupId the group ID of this t h admin
	 */
	public void setGroupId(long groupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(THAdmin thAdmin);

	public int hashCode();

	public CacheModel<THAdmin> toCacheModel();

	public THAdmin toEscapedModel();

	public String toString();

	public String toXmlString();
}